### PR TITLE
Attempt to improve the autocomplete to avoid strange race condition

### PR DESCRIPTION
**Pull request by Blacktiger**

### CODE REVIEW

**Comment by bobbyhubbard** [comment]
still broken for me. What makes you think its a race condition?

**Comment by Blacktiger** [comment]
That's just the word you used. ;) I was assuming the set calls were
happening outside the Ember run loop. Alas.

On Friday, March 27, 2015, Bobby Hubbard <notifications@github.com> wrote:

> still broken for me. What makes you think its a race condition?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetworkActionGroup/nagadmin/pull/27#issuecomment-87112107>
> .
>


-- 
Concentrate on the solution, not the problem.

**Comment by bobbyhubbard** [comment]
Oh no sorry the race condition is on the gallery. The auto-complete seems to be a problem with event propagation I think. But I still like what you have done here. :)

**Comment by bobbyhubbard** [comment]
interesting, I think I figured it out. it was the events.

**Pull request merged**
